### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by james-d-mitchell**

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@james-d-mitchell and @le27 Is this now the main development repository for AAA (Perhaps not, since there is no issue tracker here)? Who is now taking care of this package? I think you may be interested in ffloresbrito#1 . Also, you may want to migrate to https://github.com/gap-packages now and set up Travis after, to avoid fixing all URLs again later.

**Comment by james-d-mitchell** [comment]
@le27 I think this is ready to go, the test fail but this is expected since there are errors in the `PackageInfo.g` file (the warnings that appear when you load GAP. So, I suggest you squash and merge this PR, and then fix those errors.

**Comment by james-d-mitchell** [comment]
@alex-konovalov My understanding is that this is the main repo for AAA. I also suggest to @le27 that you move this to gap-packages, and then maybe we can migrate the linked issue to there?

**Comment by alex-konovalov** [comment]
Ok - I've invited @le27 to join https://github.com/orgs/gap-packages/. The linked issue needs no migration, I've just closed it. @le27 please accept invitation and migrate the repo - then get back to me and I will give you admin rights on it. We then need to remember to update `REPO_URL=https://github.com/ffloresbrito/aaa.git` in Travis tests for GAP packages to point to the new canonical location.

Good to see the progress with this project! By the way, do you have an idea about a more informative package name? Have you tried to google for "aaa gap package"? I hope that eventually it will be added to the GAP distribution, and this question may arise, so better to rename earlier. See names which other packages are choosing for inspiration: https://gap-packages.github.io/

**Comment by alex-konovalov** [comment]
@james-d-mitchell @le27 may I offer some help with demonstrating rebasing branches and merging pull requests? It would be nice to rebase this PR (or at least to squash and merge) to avoid a couple of dozens of similar commit messages with all attempts to get it working. Not only that it is less aesthetic and clear, but it could also obstruct e.g. bisecting the repository in the future.

**Pull request merged**
